# Generated by Django 4.1.7 on 2023-05-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basesite', '0002_questionvotedby_answervotedby_answer_voted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answervotedby',
            name='upvote',
        ),
        migrations.RemoveField(
            model_name='questionvotedby',
            name='upvote',
        ),
        migrations.AddField(
            model_name='answervotedby',
            name='vote',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionvotedby',
            name='vote',
            field=models.SmallIntegerField(default=0),
        ),
    ]
