# Generated by Django 4.1.7 on 2023-05-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basesite', '0003_remove_answervotedby_upvote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=64, unique=True, verbose_name='Tag text'),
        ),
    ]
