# Generated by Django 4.1.7 on 2023-05-14 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basesite', '0005_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='message',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5, 'Message is expected to contain at least 5 characters')], verbose_name='Message text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='message',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5, 'Message is expected to contain at least 5 characters')], verbose_name='Message text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(5, 'Title is expected to contain at least 5 characters')], verbose_name='Title text'),
        ),
    ]
